### ISSUE TITLE
Data attributes converted to Miso despite not being supported

### ISSUE THREAD

**Issue by itsrachelfish** [dmjio/miso-from-html#3]
Miso does not support all HTML attributes, but miso-from-html will happily turn any HTML you give it into miso syntax.

For example data attributes are converted into Miso, but it does not appear that Miso actually supports hyphenated element names

```
    parse error on input ‘data’
    |
    |   , data-toggle_ "dropdown"
    |     ^^^^
```

**Comment by dmjio** [comment]
https://github.com/dmjio/miso-from-html/pull/6
