### ISSUE TITLE
Checkboxes should be converted to `checked_`

### ISSUE THREAD

**Issue by itsrachelfish** [dmjio/miso-from-html#4]
Currently checkbox elements are converted into `textProp "checked" ""`, but it is actually more convenient to use `checked_ True` as this allows you to change the boolean value of the checkbox.

```
<input type="checkbox" checked>
```

```
[ input_
   [ type_ "checkbox"
   , textProp "checked" ""
   ]
]
```

**Comment by dmjio** [comment]
https://github.com/dmjio/miso-from-html/pull/5

**Comment by dmjio** [comment]
```bash
$ miso-from-html <<< '<input type="checkbox" checked>'
```

now becomes

```haskell
input_ 
    [ type_ "checkbox" 
    , checked_ True
    ] 
```
